version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Build debug APK
          command: ./gradlew build

      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
