# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # Requires running Emulator with Google API system image"
  desc "Capture screenshots"
  lane :screenshots do
    gradle( task: "clean assembleDebug assembleAndroidTest")
    screengrab
  end

  desc "Submit a new Beta build to the Google Play Beta track"
  lane :beta do
    gradle(task: "clean bundleRelease")
    supply(track: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    supply
  end
end
